### ISSUE TITLE
The plugin seems broken in Thunderbird, impossible to Login to ChatGPT

### ISSUE THREAD

**Issue by mistergom** [fastaddons/AI-Anywhere#11]
**Describe the bug**  
In Thunderbird, it is impossible to log in, the page refreshes and asks log in a second time and the shows a gray and empty background...
(the addon is working well in Firefox)

**Steps To Reproduce**  
1. Just try to log in to ChatGTP

**Expected behavior**  
I should log in ChatGTP and then get access to the ChatGTP engine with the bar on the left, discussion space, etc.

**Device info:**
 - operating system: Windows 11 23H2
 - Browser and version: Thunderbird 115.6.1 (64bits)
 - "AI Anywhere" version: 2.6

**Additional info**
Images with the 3 steps, log in > log in again > empty space...
![Image 01](https://github.com/fastaddons/AI-Anywhere/assets/46899060/ebaf2035-02d4-42ba-af04-9183a9fe61f1)
![Image 02](https://github.com/fastaddons/AI-Anywhere/assets/46899060/31332d84-e2b1-4da4-8055-da8e3f797d77)
![Image 03](https://github.com/fastaddons/AI-Anywhere/assets/46899060/c057dbfc-58c0-489e-9720-17dbbe7c209c)

**Comment by mistergom** [comment]
Ah! I already tried to remove and reinstall the extension, same problem again...

**Comment by Juraj-Masiar** [comment]
Hello,
Do you have some other addons installed in your Thunderbird that could interfere with network?
The addon is not handling the login, it only opens the ChatGPT login page in a modal window so that you can login so if that doesn't work, it means something else is blocking it.

**Comment by mistergom** [comment]
No and I already tried to remove all addons and so on...

But now it works again! Before the "bug", I had all my ChatGTP in a "popup window". Today I selected "new tab" for all actions, and finally I get access to the log in page (and works) via the new tab.

**Comment by mistergom** [comment]
So maybe there was an issue in the process of the log in page, "pop up" vs "new tab"...

Keep up the great work, your addon is SO useful! Thanks a lot!

**Comment by Juraj-Masiar** [comment]
They use some advance CloudFlare protection on their login page, so the login doesn't wok in the popup. That's why when you click the login button in the popup, it will be reopened it in a new window. There the login should work, and then after you are logged in, it will now work also in the popup again.

**Comment by mistergom** [comment]
Thanks for the clarification! After the successful log in, ChatGPT works fine in the pop up and in the new tab.
Thank you so much for the quick support! ;)

**Comment by R00118189** [comment]
I followed all steps above and for some reason clicking on login or signup does nothing, Login screen opens in either popup or tab (depending on setup) but there is no click functionality other than opening Terms of Use and Privacy Policy in which open in default system browser.

All add-ons disabled also so nothing non standard should block clicking on buttons

![image](https://github.com/fastaddons/AI-Anywhere/assets/6721357/a78f6d7b-1b36-4ff4-8470-6bc28ce0d3b3)

**Comment by Juraj-Masiar** [comment]
@R00118189 from the screenshot it look like you have the ChatGPT page opened in a new tab, that's good, since they prevent login from the "iframe" where the addon normally loads.
If the ChatGPT doesn't work here, it means something is broken. Either one of your other addons is preventing JavaScript from running on that page, or maybe your Thunderbird has some issue.
You can try to clear the cache (open Thunderbird settings page and search for "cache").
Also, are you using current 115 version?

**Comment by R00118189** [comment]
Yes I am using most up to date version 115.12.2 with Cache Cleared - then debugged add-on and found this

![image](https://github.com/fastaddons/AI-Anywhere/assets/6721357/dd98eeb3-1930-448d-adf3-101828d23127)

https://developer.mozilla.org/en-US/docs/Web/Privacy/Storage_Access_Policy/Errors/CookieBlockedAll

With cookies enabled I logged in.

**Comment by Juraj-Masiar** [comment]
Oh, yes, I've totally forgot about cookies / storage blocking. That will also break the page :).
Thank you for the info!
