### ISSUE TITLE
Context options are not being added. 

### ISSUE THREAD

**Issue by ioweb-gr** [fastaddons/AI-Anywhere#14]
**Describe the bug**  
I've added a few context actions however I can't make them appear on right click 

**Steps To Reproduce**  
1. Open addon settings
2. Add a new prompt
3. Tick the checkbox
4. Add context menu title
5. Open an email 
6. Right click and select the text. 
 
The option is not visible

**Expected behavior**  
The option is visible

**Device info:**
 - operating system: Windows 11 x64
 - Browser and version: 115.7.0 (64-bit)
 - "AI Anywhere" version: 2.6

**Additional info**
Add any other info about the problem here.

**Comment by Juraj-Masiar** [comment]
Don't forget to include "%s" in the prompt. It will be replaced with the selected text.
If the prompt doesn't include `%s`, then the prompt will be visible in the context menu only if NO text is selected.

I see now that this may not be so intuitive and I should make it clearer :)

**Comment by ioweb-gr** [comment]
Ah great I'll try it now :)

**Comment by ioweb-gr** [comment]
It worked great thanks :)
