### ISSUE TITLE
The text is not send to the ChatGPT server, it remains on the ChatGPT window

### ISSUE THREAD

**Issue by acescos** [fastaddons/AI-Anywhere#16]
When I write directly on ChatGPT windows or when highlight, secondary clic and open ChatGPT the arrow send button remains "sending" but nothing happens

1. I highlight text
2. I clic on the secondary button mouse, and the window of ChatGPT opens
3. The problem is the text is present on ChatGPT but it is not send text to the ChatGPT server
I expect that automatically the text is sending to the ChatGPT server

Device info:
 - operating system: Linux
 - Browser and version: Thunderbird
 - "AI Anywhere" version: last version on 2024-03-09

Previously there was no problem to use it
![image](https://github.com/fastaddons/AI-Anywhere/assets/36568488/fe68ecef-eff8-419c-986c-687e0f3f1942)

**Comment by Juraj-Masiar** [comment]
Hello,
Could you try to disable "Auto-submit query"?
![image](https://github.com/fastaddons/AI-Anywhere/assets/6358971/58a6041a-1fec-4b37-a747-a69e77c02f6a)

If it's already disabled, click it to enable it and then click it again to disable it.
Then try again to see if the input is there and if it can be submitted.

I've been testing it here but it seems to work fine. I'll try to investigate this further tomorrow.

**Comment by Juraj-Masiar** [comment]
This is likely caused by some wrongly cached data, you may need to clear cache/cookies.
I'm not sure how exactly since Thunderbird is not a "full browser". But in the Thunderbird settings you can search for "Cookies" and then filter "openai" and remove everything you see there.
That will likely log you out.

Then if that doesn't help, try to clear cache - again, use search in the settings to find "cache" and click Clear Now.

**Comment by acescos** [comment]
Hi!
Thank you for your quick reply. I have tried both paths you have suggested in your replies but is continuing the same problem.

**Comment by acescos** [comment]
I have installed the app on Firefox and Chrome. I have tried the extension but the same problem on both browers is there: it does not send request to the ChatGPT server.

**Comment by Juraj-Masiar** [comment]
That's interesting...
Is the ChatGPT page working fine for you?
https://chat.openai.com/

**Comment by acescos** [comment]
I have identified the source of the problem. It appears that the issue was not caused by your extension, but rather by the modification of the ChatGPT language, which led to the system becoming unresponsive.

![recortecito](https://github.com/fastaddons/AI-Anywhere/assets/36568488/930c066a-6f92-4a45-b5f1-38d8e001f6c2)


 I have reverted the ChatGPT language, and now everything works perfectly.

**Comment by Juraj-Masiar** [comment]
I'm not sure what you mean, but I'm happy you managed to find the cause :)
