### ISSUE TITLE
Deleted default context menu options remain 

### ISSUE THREAD

**Issue by Matthias-Loeper** [fastaddons/AI-Anywhere#17]
**Describe the bug**  
When I delete all context menu options shipped with the addon, in some cases they are used although I called a context menu option added by myself. 

**Steps To Reproduce**  
1. Install the addon, allow in private tabs
2. delete all context menu options shipped with the addon ("Explain", "Translate...", ...)
3. Add your own context menu option using %s. Example: "Summarize the following text in about 100 words. Here is the text : %s"
4. Set "context menu click will open" -> "new tab"
5. Login to ChatGPT+
6. Open a webpage, mark text, right click, choose context menu option.
--> Now sometimes a new window opens instead of a new tab (see 4.). The prompt is not the one set in 3., but one of the preconfigured ones, e.g. "Explain"

**Expected behavior**  
When I set "context menu click will open" to "new tab", a new window should not be opened, but a new tab. 
After selecting context menu items defined by the user, the prompts defined in those items should be sent to ChatGPT.

**Device info:**
- Windows 10
- Firefox ESR 115.11.0 portable (resides on Drive C:\)
- AI Anywhere version 3.3

**Additional info**
Happens too in Firefox 126.0.1 

https://github.com/fastaddons/AI-Anywhere/assets/127855621/15b731ab-c24e-417d-b308-1079580ca0b8

**Comment by Juraj-Masiar** [comment]
I've just released new version 3.4 that fixes a race condition that likely caused also this issue.
Please let me know if this is still happening.

**Comment by Matthias-Loeper** [comment]
Sorry for late replying. 
Works in Version 3.5. Thank you very much!
