### ISSUE TITLE
Click twice and 4o?

### ISSUE THREAD

**Issue by mistergom** [fastaddons/AI-Anywhere#18]
Hello!

I use the plugin with Thunderbird and I noticed that, since the last version, I have to click twice "Ai anywhere" in the context menu to get the window or popup.

And could you please implement ChatGPT 4o in the options?

Thanks a lot and keep up the great and so useful work! ;)

**Comment by Juraj-Masiar** [comment]
Hello,
Thanks for reporting.
I'll try to fix it today.
And I'll see if the ChatGPT 4o can be done too.

**Comment by mistergom** [comment]
Oh great! ;)

**Comment by Juraj-Masiar** [comment]
So, about the ChatGPT 4o, can you send me the URL used by that model?
Fore example, the default model uses:
https://chatgpt.com/?model=auto
The 4.0 should use something like this:
https://chatgpt.com/?model=gpt-4

Since I don't have the premium version, I can't check...

**Comment by mistergom** [comment]
Ok, I have this:
https://chatgpt.com/?model=gpt-4o

**Comment by Juraj-Masiar** [comment]
Done, new version 3.4 was just released and should fix the issue with not working first click and also adds gpt-4o option.
You can check for updates from Add-ons manager page:
![image](https://github.com/fastaddons/AI-Anywhere/assets/6358971/a5652fd7-b4f2-466d-ad22-9b58591084eb)

**Comment by mistergom** [comment]
Everything is ok, thanks! Works very well!
