### ISSUE TITLE
Auto submit not working

### ISSUE THREAD

**Issue by Narnia-Nitro** [fastaddons/AI-Anywhere#19]
**Describe the bug**  
Auto submit query is not working.  It used to work until one of the updates several weeks back.

**Steps To Reproduce**  
1.  Click box to activate "Auto submit query" in settings
2. Submit query
3. ChatGPT popup opens up as expected and the query is inputted into the ChatGPT query box, but in order to send the query, I need to manually click on the send button before ChatGPT generates a response.

**Expected behavior**  
I expect to be able to have the query sent to ChatGPT and auto submitted without my need to manually click on any buttons within the ChatGPT popup window in order to see ChatGPT's generated response.

**Device info:**

Windows 11
Tried both on Firefox 127 and Edge 126 with Anywhere AI version 3.4 on each.  Auto submit query is not working on either.

**Comment by Juraj-Masiar** [comment]
Thank you for the report.
I'll try to fix it by the end of the week.

**Comment by Juraj-Masiar** [comment]
Fixed in 3.5 version. They've changed a bit their page so I had to adjust the submit button lookup.
You should receive update soon. Firefox version is already approved in the store, Chrome/Edge is being reviewed.
Thank you for reporting!
Have a nice weekend :)
