### ISSUE TITLE
Model GPT-4 by default instead 3.5

### ISSUE THREAD

**Issue by A-y-R-e** [fastaddons/AI-Anywhere#4]
Dear Juraj Mäsiar,
Thank you for creating AI Anywhere for ChatGPT. Your work is truly appreciated and extremely useful to the community.
I'm using the plug-in "AI Anywhere for ChatGPT 1.9" in Thunderbird 102.10.1

**Is your feature request related to a problem? Please describe.**
For those of us who have access to GPT-4 there should be a way to access it in the plug-in window by default, not 3.5. it is frustrating to change it for each query manually and have to copy and paste the text beforehand. You lose the workflow of the plug-in completely.

**Describe the solution you'd like**
Change the default url in the window that opens the plug-in to the one that goes directly to GPT-4:(https://chat.openai.com/?model=gpt-4)

**Comment by Juraj-Masiar** [comment]
Hello,
I've added new option in version 2.0:
![image](https://user-images.githubusercontent.com/6358971/235448588-5e2eb798-c960-4c6b-bc26-b26fee09b4a5.png)

I can't test it since I don't have the premium subscription so fingers crossed :)

**Comment by A-y-R-e** [comment]
Thank you very much for the fast update Juraj-Masiar. 

I confirm you that the new option to use GPT-4 by default works fine, **BUT only if you use the standard options (with container)**:
New window
Popup window
New tab

In all "without container" options you still get the GPT3.5 version even if you have GPT4 selected in the settings:
New window (without container)
New tab (without container)

So now I can use GPT-4 in standard modes, which is enough for me, but keep that in mind for a future revision!

Best regards and happy workers' day, where some of us are still working ;)
_AyRe_

**Comment by Juraj-Masiar** [comment]
Oh... dummy me!
Yeah, I've forgot to change it on other places... (or in other words, my architecture was wrong).
Fixed in 2.1, deploying now...

**Comment by A-y-R-e** [comment]
Current version 2.1: Everything works fine now, in any mode ;)
Oh my God, this is what it means to be committed to the job!

Thanks Juraj-Masiar!

**Comment by Juraj-Masiar** [comment]
No problem, I'm happy it works :)
And happy "workers' day" to you too! 
I've been sick the whole last week so I was eager to get back to work - holiday or not :)
