### ISSUE TITLE
Only the first line of the selected text is copied from thunderbird

### ISSUE THREAD

**Issue by badpenguin** [fastaddons/AI-Anywhere#5]
Linux Mint
ii  thunderbird                               1:102.10.0+build2-0ubuntu0.22.04.1
ii  thunderbird-gnome-support                 1:102.10.0+build2-0ubuntu0.22.04.1
ii  thunderbird-locale-en                     1:102.10.0+build2-0ubuntu0.22.04.1
ii  thunderbird-locale-en-us                  1:102.10.0+build2-0ubuntu0.22.04.1
ii  thunderbird-locale-it                     1:102.10.0+build2-0ubuntu0.22.04.1

**Comment by Juraj-Masiar** [comment]
Not exactly, all lines should be there, it's just the input doesn't resize so you can't see other lines.
If you press "space" or make any other changes to the text, it will resize.
I'll see what I can do about it so that it resizes automatically.

**Comment by Juraj-Masiar** [comment]
Fixed in 2.2 version.
