### ISSUE TITLE
Thunderbird: Login button does nothing

### ISSUE THREAD

**Issue by ploebb** [fastaddons/AI-Anywhere#6]
**Describe the bug**  
After installing the plugin, the login-page of openai appears, but the buttons (Login, Signup) do nothing. Same behavior after a restart of thunderbird and going to the AI-Anywhere settings.

**Device info:**
 - operating system: Windows 10
 - Browser and version: Thunderbird 102.11.0 (latest)
 - "AI Anywhere" version: 2.2

**Additional info**
![grafik](https://github.com/fastaddons/AI-Anywhere/assets/5870131/e6385b03-5346-46f3-baf7-215ce8a697e0)

**Comment by Juraj-Masiar** [comment]
There seems to be some kind of delay, I've tired it now and it took it about 5 or 10 seconds to react.
If not, could you try to close it and reopen it again?
I don't think I can fix this though since the login is fully handled by the ChatGPT website.

**Comment by ploebb** [comment]
Thanks for the quick reply. I waited a few minutes and restarted my machine but still no luck. The login on https://chat.openai.com/auth/login works fine though.

Is there any way to get a developer console or something for the login window to debug that further?

**Comment by Juraj-Masiar** [comment]
To open debugger, press "Ctrl + Shift + i". However, it won't work when the login window is focused (yet another bug in Thunderbird), so you need to focus main Thunderbird window first.
Then when the debugger is opened, click the Console window - that may show some errors, especially once you click the Login button.

**Comment by ploebb** [comment]
Thanks, I got the debugger open. After loading the popup, nothing is happening in the network analyzer or the error console. Maybe some javascript gets blocked? I did not find a setting in thunderbird in that regard.

![grafik](https://github.com/fastaddons/AI-Anywhere/assets/5870131/b3755ee8-6309-4036-8a7a-a2e789deca78)

**Comment by ploebb** [comment]
I just tried with a blank thunderbird profile and it works fine there. So it's probably some addon or setting that interferes with the login page. I'll report back, if I find it.

**Comment by ploebb** [comment]
Okay something (possibly myself) disabled javascript in the advanced settings. I just enabled it and it works fine now. Thanks for your help! I guess we can close this. 

![grafik](https://github.com/fastaddons/AI-Anywhere/assets/5870131/a3d312ae-996a-4171-9953-f470997e981a)

**Comment by Juraj-Masiar** [comment]
Nice! How did you discovered that, crazy :)

**Comment by ploebb** [comment]
Just had a hunch 😄
